version: 0.2
phases:
  pre_build:
    commands:
      - pip install --upgrade awscli
      - dotnet restore Brian.Ai.WebApp/Brian.Ai.WebApp.csproj
  build:
    commands:
      - dotnet publish -c release -o ./build_output Brian.Ai.WebApp/Brian.Ai.WebApp.csproj
artifacts:
  files:
    - template.yml
    - Brian.Ai.WebApp/build_output/**/*
    - scripts/**/*
    - appspec.yml
